name: Deploy

on:
  push:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  build-deploy:
    
    runs-on: [self-hosted]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      # Installs rust stable toolchain for ARM64
      - name: Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: aarch64-unknown-linux-gnu
          override: true
          default: true
          
      - name: Cache
        uses: Swatinem/rust-cache@v1

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target aarch64-unknown-linux-gnu
        
      - name: SCP to server
        uses: garygrossgarten/github-action-scp@release
        with:
          local: target/aarch64-unknown-linux-gnu/release/parakeet-bot
          remote: bot
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.SSHKEY}}
          port: ${{ secrets.PORT }}

      - name: Restart Service
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.SSHKEY}}
          port: ${{ secrets.PORT }}
          command: |
            tmux kill-session -t
            chmod u+x bot
            tmux new-session -s bot-session ./bot