name: Deploy

on:
  push:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  build-deploy:
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      # Installs rust stable toolchain for ARM64
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: aarch64-unknown-linux-gnu
          override: true
          default: true
          
      # Use caching for faster builds
      - uses: Swatinem/rust-cache@v1

      - name: Make release build
        run: cargo build --release
        
      - name: SCP to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          port: ${{ secrets.PORT }}
          source: "target/release/parakeet-bot"
          target: "bot" 
