name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: Make release build
        run: cargo build --release
        
      - name: SCP to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "target/release/parakeet-bot"
          target: "bot" 
